name: Dependency check

on:
  schedule:
    - cron: '0 6 */2 * *' # “At 06:00 on every 2nd day-of-month.”
  push:
    branches: [ main ]
    paths: [ '.github/workflows/**', '*.gradle.kts', '*.properties' ]
  pull_request:
    branches: [ main ]
    paths: [ '.github/workflows/**', '*.gradle.kts', '*.properties' ]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache the build
        uses: actions/cache@v2
        with:
          path: ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-gradle-owasp
          restore-keys: ${{ runner.os }}-gradle-owasp
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Analyze dependencies
        run: ./gradlew dependencyCheckAnalyze